### ISSUE TITLE
python-ruamel.yaml insists on installing with pip

### ISSUE THREAD

**Issue by fredmanglis** [fredmanglis/guix-conda#1]
When trying to install python-conda-executable, one of the dependencies, python-ruamel.yaml fails, insisting that one must use pip to install it.

Figure out how to install the built code with pip, on guix

**Comment by jsierles** [comment]
Can this be worked around by importing this dependency directly into guix?

I don't see an error related to pip, but instead:

```
phase `build' succeeded after 10.4 seconds
starting phase `check'
running "python setup.py" with command "test" and parameters ()
sys.argv ['-c', 'test']
test compiling test_ruamel_yaml
running test
running egg_info
writing top-level names to ruamel.yaml.egg-info/top_level.txt
writing ruamel.yaml.egg-info/PKG-INFO
writing dependency_links to ruamel.yaml.egg-info/dependency_links.txt
deleting ruamel.yaml.egg-info/requires.txt
writing namespace_packages to ruamel.yaml.egg-info/namespace_packages.txt
warning: manifest_maker: standard file '-c' not found

reading manifest file 'ruamel.yaml.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ruamel.yaml.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.5/_ruamel_yaml.cpython-35m-x86_64-linux-gnu.so ->
.ruamel (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: .ruamel (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: .ruamel
Traceback (most recent call last):
  File "/gnu/store/3aw9x28la9nh8fzkm665d7fywxzbl15j-python-3.5.3/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/gnu/store/3aw9x28la9nh8fzkm665d7fywxzbl15j-python-3.5.3/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
ImportError: No module named '.ruamel'
```

**Comment by fredmanglis** [comment]
Oh, this issue was for an earlier trial while defining the package. The error you got is also what I get currently and I'm trying to figure it out too.

**Comment by fredmanglis** [comment]
This issue is no longer relevant, seeing as conda has now been on mainline guix for a while.
